### PR TITLE
add: issue #191 - Portfolio-template

### PR DESCRIPTION
**Pull request by AE-Hertz**
deployment  link - https://animata-issue-191.vercel.app/

### CODE REVIEW

**Comment by AE-Hertz** [comment]
@hari @sudhashrestha can you please make a standalone repo so that I can send PR there. Thank you.

**Comment by AE-Hertz** [comment]
@hari @sudhashrestha hello , its been days i requested for PRs, can you please create a dev branch so PR can be merged their, i am really into hacktoberfest'24 🙂

**Comment by hari** [comment]
@AE-Hertz This PR will not be merged into this repo. I will create a new dedicated repo for this one and invite you.

**Comment by AE-Hertz** [comment]
@hari  yes, and please make sure that repo is included in hacktoberfest'24 thank you

**Pull request closed without merging**
