### PR TITLE
feat(comment-reply): adds comment-reply card

### PR DESCRIPTION
**Pull request by prince981620**
https://github.com/user-attachments/assets/2d487b09-835b-43d6-86bb-cf633f93656e

hey @hari i have added comment-reply component in card sections . please review

### CODE REVIEW

**Comment by hari** [comment]
@prince981620 the UI is shifting, could you try to improve it?

**Comment by prince981620** [comment]
> @prince981620 the UI is shifting, could you try to improve it?

@hari recreated component from scratch fixing that shifting UI. please review

**Review by hari — CHANGES_REQUESTED** [review]
@prince981620 Please fix the typo of `reply` and use layoutId to improve the animation. https://www.framer.com/motion/layout-animations. You might also need an extra view to make the animation look like the one in the video.

**Comment by prince981620** [comment]
> @prince981620 Please fix the typo of `reply` and use layoutId to improve the animation. https://www.framer.com/motion/layout-animations. You might also need an extra view to make the animation look like the one in the video.

hey @hari i have fixed the typo and also fixed the animation. kindly review.

**Comment by prince981620** [comment]
@hari  review ??

**Comment by hari** [comment]
@prince981620 this is not responsive

**Comment by prince981620** [comment]
> @prince981620 this is not responsive

hey @hari added responsiveness to the input box. kindly review

**Review by hari — APPROVED** [review]
@prince981620 We can improve the design a little bit, especially padding and spacing. You can create a new PR if you would like to, I am going to merge this.

**Comment by prince981620** [comment]
> @prince981620 We can improve the design a little bit, especially padding and spacing. You can create a new PR if you would like to, I am going to merge this.

@hari sure I will give it a try.

**Pull request merged**
