### PR TITLE
checklist-completion.tsx

### PR DESCRIPTION
**Pull request by ShoomanKhatri**
I think it is working but  max-w-lg  or  max width is not working for some reasons.

### CODE REVIEW

**Comment by hari** [comment]
```

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "docs/progress/checklist-completion.mdx": UnexpectedMDXError: YAMLException: the stream contains non-printable characters at line 3, column 111:
          ...  completed steps, and a counter.
                                              ^
                                              ```

**Review by hari — CHANGES_REQUESTED** [review]
@ShoomanKhatri the PR contains unrelated files

**Comment by ShoomanKhatri** [comment]
Bro, I'm new to GitHub contributions and would appreciate some guidance.

**Comment by hari** [comment]
@ShoomanKhatri Please create a new PR with only "related files" or restore the unrelated files.

**Review by hari — CHANGES_REQUESTED** [review]
Unrelated files have been removed.

**Comment by ShoomanKhatri** [comment]
okay

**Pull request closed without merging**
