### PR TITLE
feat(card): add Webhooks-card 008#223

### PR DESCRIPTION
**Pull request by Pavankumar07s**
issue number :#223
Checklist
 I have read and followed the contributing guidelines.
 I have developed the component according to the requirements.
 I have tested the component across different browsers and screen sizes.
 I have documented the component for future reference.
 I have submitted a pull request with appropriate labels and referenced this issue number.

All done ...

### CODE REVIEW

**Comment by Pavankumar07s** [comment]
hey @hari @sudhashrestha review my card.

**Review by hari — APPROVED** [review]

**Comment by hari** [comment]
Please make this responsive.

**Comment by Pavankumar07s** [comment]
Alright @hari

**Comment by hari** [comment]
🚀 Preview deployed to:

**Comment by hari** [comment]
🚀 Preview deployed to:

**Comment by hari** [comment]
🚀 Preview deployed to: https://51ff48c0.animata.pages.dev

**Comment by hari** [comment]
🚀 Preview deployed to: https://dev-dev.animata.pages.dev

**Pull request merged**
