### PR TITLE
feat(faq-section): add faq in accordion

### PR DESCRIPTION
**Pull request by anshuman008**
created the faq section!

https://github.com/user-attachments/assets/d60e4a90-035b-44aa-8f2b-a59585d646ac

### CODE REVIEW

**Comment by anshuman008** [comment]
Uploading Screen Recording 2024-10-06 at 6.26.30 PM.mov…

**Review by hari — CHANGES_REQUESTED** [review]
@anshuman008 Could you use radix-ui accordion as wrapper so that it is accessible? 

https://www.radix-ui.com/primitives/docs/components/accordion

**Comment by anshuman008** [comment]
done sirr now im added radix-ui accordion as wrapper

**Review by hari — APPROVED** [review]

**Comment by anshuman008** [comment]
hey @hari @sudhashrestha  can you please close this issue #307 coz its already merged

**Pull request merged**
